### ISSUE TITLE
Wrong field used in analysis.js 

### ISSUE THREAD

**Issue by varunjm** [CSC-510/Complexity#1]
The `builders[fileBuilder.filePath] = fileBuilder` in line 113 of [analysis.js](https://github.com/CSC-510/Complexity/blob/master/analysis.js) contains a erroneous/Non-existent field `filePath`. This makes it equivalent to `builders['undefined'] = filePath`.
It should probably be  `builders[fileBuilder.FileName] = fileBuilder`

**Comment by chrisparnin** [comment]
Fixed in: https://github.com/CSC-510/Complexity/commit/05932d8f62d7c2a535e7075aa0de4ca93ed1e545

Next time consider a pull request!
